# Generated by Django 3.1.5 on 2021-01-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210127_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='id',
        ),
        migrations.AlterField(
            model_name='letter',
            name='published_date',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='title',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
