# Generated by Django 3.1.5 on 2021-01-27 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210127_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
