# Generated by Django 3.1.5 on 2021-01-28 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_letter_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='category',
        ),
    ]
