# Generated by Django 3.1.5 on 2021-01-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_letter_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='category',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
